#!/bin/sh

D_ENABLE_HLS_CSYNTH_=$(grep D_ENABLE_HLS_CSYNTH_= ../CFLAGS|cut -d'=' -f2)
D_ENABLE_HLS_CSIM_=$(grep D_ENABLE_HLS_CSIM_= ../CFLAGS|cut -d'=' -f2)
D_ENABLE_HLS_COSIM_=$(grep D_ENABLE_HLS_COSIM_= ../CFLAGS|cut -d'=' -f2)
D_DEPTH_=$(grep D_DEPTH_= ../CFLAGS|cut -d'=' -f2)
D_MM_CHANNELS_=$(grep D_MM_CHANNELS_= ../CFLAGS|cut -d'=' -f2)
D_MM_PPC_=$(grep D_MM_PPC_= ../CFLAGS|cut -d'=' -f2)
D_STRM_INTR_PPC_=$(grep D_STRM_INTR_PPC_= ../CFLAGS|cut -d'=' -f2)
D_STRM_OUT_CHANNELS_=$(grep D_STRM_OUT_CHANNELS_= ../CFLAGS|cut -d'=' -f2)
D_STRM_OUT_PPC_=$(grep D_STRM_OUT_PPC_= ../CFLAGS|cut -d'=' -f2)
D_STRM_IN_CHANNELS_=$(grep D_STRM_IN_CHANNELS_= ../CFLAGS|cut -d'=' -f2)
D_STRM_IN_PPC_=$(grep D_STRM_IN_PPC_= ../CFLAGS|cut -d'=' -f2)
D_FP_T_=$(grep D_FP_T_= ../CFLAGS|cut -d'=' -f2)
D_MAX_COLS_=$(grep D_MAX_COLS_= ../CFLAGS|cut -d'=' -f2)
D_MAX_ROWS_=$(grep D_MAX_ROWS_= ../CFLAGS|cut -d'=' -f2)
D_MAX_STRIDE_=$(grep D_MAX_STRIDE_= ../CFLAGS|cut -d'=' -f2)
D_COLS_MARGIN_=$(grep D_COLS_MARGIN_= ../CFLAGS|cut -d'=' -f2)
D_ROWS_MARGIN_=$(grep D_ROWS_MARGIN_= ../CFLAGS|cut -d'=' -f2)
D_BLOCK_SIZE_=$(grep D_BLOCK_SIZE_= ../CFLAGS|cut -d'=' -f2)
D_VIDWRAXI_NUM_WRITE_OUTSTANDING_=$(grep D_VIDWRAXI_NUM_WRITE_OUTSTANDING_= ../CFLAGS|cut -d'=' -f2)
D_AFFRDAXI_NUM_READ_OUTSTANDING_=$(grep D_AFFRDAXI_NUM_READ_OUTSTANDING_= ../CFLAGS|cut -d'=' -f2)
D_AFFWRAXI_NUM_WRITE_OUTSTANDING_=$(grep D_AFFWRAXI_NUM_WRITE_OUTSTANDING_= ../CFLAGS|cut -d'=' -f2)
D_VIDRDAXI_NUM_READ_OUTSTANDING_=$(grep D_VIDRDAXI_NUM_READ_OUTSTANDING_= ../CFLAGS|cut -d'=' -f2)
D_VIDWRAXI_LATENCY_=$(grep D_VIDWRAXI_LATENCY_= ../CFLAGS|cut -d'=' -f2)
D_AFFRDAXI_LATENCY_=$(grep D_AFFRDAXI_LATENCY_= ../CFLAGS|cut -d'=' -f2)
D_AFFWRAXI_LATENCY_=$(grep D_AFFWRAXI_LATENCY_= ../CFLAGS|cut -d'=' -f2)
D_VIDRDAXI_LATENCY_=$(grep D_VIDRDAXI_LATENCY_= ../CFLAGS|cut -d'=' -f2)

D_ID_=$(cat ../ID)
D_TOP_=$(cat ../TOP)_Id${D_ID_}

CFLAGS=""
CFLAGS="$CFLAGS -DD_ENABLE_HLS_CSYNTH_=$D_ENABLE_HLS_CSYNTH_"
CFLAGS="$CFLAGS -DD_ENABLE_HLS_CSIM_=$D_ENABLE_HLS_CSIM_"
CFLAGS="$CFLAGS -DD_ENABLE_HLS_COSIM_=$D_ENABLE_HLS_COSIM_"
CFLAGS="$CFLAGS -DD_DEPTH_=$D_DEPTH_"
CFLAGS="$CFLAGS -DD_MM_CHANNELS_=$D_MM_CHANNELS_"
CFLAGS="$CFLAGS -DD_MM_PPC_=$D_MM_PPC_"
CFLAGS="$CFLAGS -DD_STRM_OUT_CHANNELS_=$D_STRM_OUT_CHANNELS_"
CFLAGS="$CFLAGS -DD_STRM_OUT_PPC_=$D_STRM_OUT_PPC_"
CFLAGS="$CFLAGS -DD_STRM_IN_CHANNELS_=$D_STRM_IN_CHANNELS_"
CFLAGS="$CFLAGS -DD_STRM_INTR_PPC_=$D_STRM_INTR_PPC_"
CFLAGS="$CFLAGS -DD_STRM_IN_PPC_=$D_STRM_IN_PPC_"
CFLAGS="$CFLAGS -DD_FP_T_=$D_FP_T_"
CFLAGS="$CFLAGS -DD_MAX_COLS_=$D_MAX_COLS_"
CFLAGS="$CFLAGS -DD_MAX_ROWS_=$D_MAX_ROWS_"
CFLAGS="$CFLAGS -DD_MAX_STRIDE_=$D_MAX_STRIDE_"
CFLAGS="$CFLAGS -DD_COLS_MARGIN_=$D_COLS_MARGIN_"
CFLAGS="$CFLAGS -DD_ROWS_MARGIN_=$D_ROWS_MARGIN_"
CFLAGS="$CFLAGS -DD_BLOCK_SIZE_=$D_BLOCK_SIZE_"
CFLAGS="$CFLAGS -DD_VIDWRAXI_NUM_WRITE_OUTSTANDING_=$D_VIDWRAXI_NUM_WRITE_OUTSTANDING_"
CFLAGS="$CFLAGS -DD_AFFRDAXI_NUM_READ_OUTSTANDING_=$D_AFFRDAXI_NUM_READ_OUTSTANDING_"
CFLAGS="$CFLAGS -DD_AFFWRAXI_NUM_WRITE_OUTSTANDING_=$D_AFFWRAXI_NUM_WRITE_OUTSTANDING_"
CFLAGS="$CFLAGS -DD_VIDRDAXI_NUM_READ_OUTSTANDING_=$D_VIDRDAXI_NUM_READ_OUTSTANDING_"
CFLAGS="$CFLAGS -DD_VIDWRAXI_LATENCY_=$D_VIDWRAXI_LATENCY_"
CFLAGS="$CFLAGS -DD_AFFRDAXI_LATENCY_=$D_AFFRDAXI_LATENCY_"
CFLAGS="$CFLAGS -DD_AFFWRAXI_LATENCY_=$D_AFFWRAXI_LATENCY_"
CFLAGS="$CFLAGS -DD_VIDRDAXI_LATENCY_=$D_VIDRDAXI_LATENCY_"

CFLAGS="$CFLAGS -DD_TOP_=$D_TOP_"

while read LINE; do
  if [[ "$LINE" =~ ^-I ]]; then
    CFLAGS="$CFLAGS $LINE"
  fi
done <../CFLAGS

LINE=""
