#!/bin/sh

D_ENABLE_HLS_CSIM_OBSOLETE_=$(grep D_ENABLE_HLS_CSIM_OBSOLETE_= ../CSIMFLAGS|cut -d'=' -f2)
D_GOLDENANGLE_=$(grep D_GOLDENANGLE_= ../CSIMFLAGS|cut -d'=' -f2)

CSIMFLAGS=""
CSIMFLAGS="$CSIMFLAGS -DD_ENABLE_HLS_CSIM_OBSOLETE_=$D_ENABLE_HLS_CSIM_OBSOLETE_"
CSIMFLAGS="$CSIMFLAGS -DD_GOLDENANGLE_=$D_GOLDENANGLE_"

while read LINE; do
  if [[ "$LINE" =~ ^-I/ ]]; then
    CSIMFLAGS="$CSIMFLAGS $LINE"
  fi
done <../CSIMFLAGS

LINE=""
