#!/bin/sh

D_ENABLE_HLS_CSYNTH_OBSOLETE_=$(grep D_ENABLE_HLS_CSYNTH_OBSOLETE_= ../CSYNTHFLAGS|cut -d'=' -f2)

CSYNTHFLAGS=""
CSYNTHFLAGS="$CSYNTHFLAGS -DD_ENABLE_HLS_CSYNTH_OBSOLETE_=$D_ENABLE_HLS_CSYNTH_OBSOLETE_"

while read LINE; do
  if [[ "$LINE" =~ ^-I/ ]]; then
    CSYNTHFLAGS="$CSYNTHFLAGS $LINE"
  fi
done <../CSYNTHFLAGS

LINE=""
