#!/bin/sh

D_DEPTH_=$(grep D_DEPTH_= ../CFLAGS|cut -d'=' -f2)
D_COLOR_CHANNELS_=$(grep D_COLOR_CHANNELS_= ../CFLAGS|cut -d'=' -f2)
D_MM_PPC_=$(grep D_MM_PPC_= ../CFLAGS|cut -d'=' -f2)
D_STRM_PPC_=$(grep D_STRM_PPC_= ../CFLAGS|cut -d'=' -f2)
D_MAX_ROWS_=$(grep D_MAX_ROWS_= ../CFLAGS|cut -d'=' -f2)
D_MAX_COLS_=$(grep D_MAX_COLS_= ../CFLAGS|cut -d'=' -f2)
D_MAX_STRIDE_=$(grep D_MAX_STRIDE_= ../CFLAGS|cut -d'=' -f2)
D_COLS_MARGIN_=$(grep D_COLS_MARGIN_= ../CFLAGS|cut -d'=' -f2)
D_ROWS_MARGIN_=$(grep D_ROWS_MARGIN_= ../CFLAGS|cut -d'=' -f2)
D_BLOCK_SIZE_=$(grep D_BLOCK_SIZE_= ../CFLAGS|cut -d'=' -f2)

D_ID_=$(cat ../ID)
D_TOP_=$(cat ../TOP)_Id${D_ID_}

CFLAGS=""
CFLAGS="$CFLAGS -DD_DEPTH_=$D_DEPTH_"
CFLAGS="$CFLAGS -DD_COLOR_CHANNELS_=$D_COLOR_CHANNELS_"
CFLAGS="$CFLAGS -DD_MM_PPC_=$D_MM_PPC_"
CFLAGS="$CFLAGS -DD_STRM_PPC_=$D_STRM_PPC_"
CFLAGS="$CFLAGS -DD_MAX_ROWS_=$D_MAX_ROWS_"
CFLAGS="$CFLAGS -DD_MAX_COLS_=$D_MAX_COLS_"
CFLAGS="$CFLAGS -DD_MAX_STRIDE_=$D_MAX_STRIDE_"
CFLAGS="$CFLAGS -DD_COLS_MARGIN_=$D_COLS_MARGIN_"
CFLAGS="$CFLAGS -DD_ROWS_MARGIN_=$D_ROWS_MARGIN_"
CFLAGS="$CFLAGS -DD_BLOCK_SIZE_=$D_BLOCK_SIZE_"
CFLAGS="$CFLAGS -DD_TOP_=$D_TOP_"
