#!/bin/sh

D_ENABLE_HLS_COSIM_OBSOLETE_=$(grep D_ENABLE_HLS_COSIM_OBSOLETE_= ../COSIMFLAGS|cut -d'=' -f2)

COSIMFLAGS=""
COSIMFLAGS="$COSIMFLAGS -DD_ENABLE_HLS_COSIM_OBSOLETE_=$D_ENABLE_HLS_COSIM_OBSOLETE_"

while read LINE; do
  if [[ "$LINE" =~ ^-I ]]; then
    COSIMFLAGS="$COSIMFLAGS $LINE"
  fi
done <../COSIMFLAGS

LINE=""
