#!/bin/sh

D_ENABLE_C_SIMULATION_=$(grep D_ENABLE_C_SIMULATION_= ../CSIMFLAGS|cut -d'=' -f2)
D_ENABLE_C_SIMULATION_DEBUG_=$(grep D_ENABLE_C_SIMULATION_DEBUG_= ../CSIMFLAGS|cut -d'=' -f2)
D_ENABLE_C_SIMULATION_NONSYNTHESIS_CONSTRUCTS_=$(grep D_ENABLE_C_SIMULATION_NONSYNTHESIS_CONSTRUCTS_= ../CSIMFLAGS|cut -d'=' -f2)

CSIMFLAGS=""
CSIMFLAGS="$CSIMFLAGS -DD_ENABLE_C_SIMULATION_=$D_ENABLE_C_SIMULATION_"
CSIMFLAGS="$CSIMFLAGS -DD_ENABLE_C_SIMULATION_DEBUG_=$D_ENABLE_C_SIMULATION_DEBUG_"
CSIMFLAGS="$CSIMFLAGS -DD_ENABLE_C_SIMULATION_NONSYNTHESIS_CONSTRUCTS_=$D_ENABLE_C_SIMULATION_NONSYNTHESIS_CONSTRUCTS_"

while read LINE; do
  if [[ "$LINE" =~ ^-I/ ]]; then
    CSIMFLAGS="$CSIMFLAGS $LINE"
  fi
done <../CSIMFLAGS

LINE=""
